[package]
name = "cifrahomophonica"
version = "1.0.0"
authors = ["Robert Fuszenecker <robert.fuszenecker@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
